## Importing Basic Libraries

In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Visualization
import matplotlib.pyplot as plt

# Machine Learning
from sklearn.model_selection import train_test_split
from sklearn.decomposition import PCA
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn import metrics

## PIL (Python Image Library)

In [2]:
from PIL import Image, ImageFilter, ImageDraw, ImageFont

In [3]:
# open and show image
image1 = Image.open("dataset/68950.png")
image1.show() # displays numpy array as image

In [4]:
# add image filters
image1_e = image1.filter(ImageFilter.EMBOSS())
image1_b = image1.filter(ImageFilter.BLUR())
image1_e.show()
image1_b.show()

In [5]:
# draw on image
canvas = ImageDraw.Draw(image1)
canvas.rectangle((100, 200, 550, 650), outline = (0, 255, 2), width = 10)
canvas.line((100, 200, 550, 650), fill = (255, 2, 0), width = 5)
image1.show()

In [6]:
myfont = ImageFont.truetype("arial.ttf", 60)
canvas.text((250, 650), "This is a pretty face.", font = myfont, fill = (0,0,255))
image1.show()

## Face Recognition Library

In [7]:
import face_recognition as fr

In [8]:
img1 = fr.load_image_file("dataset/68951.png") # load image file as default RBG
img2 = fr.load_image_file("dataset/68952.png", "RGB") # loads in RGB
img3 = fr.load_image_file("dataset/68953.png", "L") # loads as black and white
print(img1.shape, img2.shape, img3.shape)

(1024, 1024, 3) (1024, 1024, 3) (1024, 1024)


In [9]:
# images loaded as numpy arrays of numerical pixel values
print(img2[0]) # 1/1024th representation of image

[[187 185 173]
 [188 186 174]
 [190 188 175]
 ...
 [185 187 177]
 [192 193 184]
 [176 178 167]]


In [10]:
# convert numpy values back to image 
image2 = Image.fromarray(img2)
image2.show()

#### Face Locations
Returns list of tuples of (top, right, bottom, left) coordinates of all faces in the image

In [11]:
people = fr.load_image_file("dataset/69001.jpg")
print(people.shape)

(2047, 1365, 3)


In [12]:
# extracting each face from image coordinates
def extract_face(l):
    for i in range(len(l)):
        top, right, bottom, left = l[i]
        face = people[top:bottom, left:right]
        print(face.shape)
        face_image =  Image.fromarray(face)
        face_image.show()

In [13]:
# drawing rectangles around faces
def drawrect(image, l):
    face = Image.fromarray(image)
    for i in range(len(l)):
        top, right, bottom, left = l[i]
        face_rect = ImageDraw.Draw(face)
        face_rect.rectangle((left, top, right, bottom), outline = (255, 0, 0), width = 10)
    face.show()

In [14]:

l = fr.face_locations(people) # default model: hog
# lhog = fr.face_locations(people, model = 'hog') 
print(l)
extract_face(l)

[(804, 589, 1189, 204), (247, 1103, 632, 718), (848, 1097, 1169, 776)]
(385, 385, 3)
(385, 385, 3)
(321, 321, 3)


In [15]:
lcnn = fr.face_locations(people, model = 'cnn')
print(lcnn)
extract_face(lcnn)

[(849, 1087, 1143, 793), (245, 1095, 667, 672), (801, 581, 1224, 158)]
(294, 294, 3)
(422, 423, 3)
(423, 423, 3)


In [16]:
drawrect(people, l)
drawrect(people, lcnn)

#### Face Encodings
Returns list of 128 float numpy array face encodings for each face in image

In [17]:
encodings_people = fr.face_encodings(people)
print(len(encodings_people))
print(len(encodings_people[0]))
print(encodings_people)

3
128
[array([-0.11614306, -0.05022058,  0.01374533, -0.07499997, -0.08884497,
       -0.10591253,  0.00906487, -0.08037573,  0.20751841, -0.10623221,
        0.11830029,  0.01911241, -0.27976558, -0.04688681,  0.00211527,
        0.16835058, -0.16371155, -0.14428803, -0.10225864, -0.03682549,
        0.03956093,  0.02909841,  0.06635259,  0.14052887, -0.10157414,
       -0.28596994, -0.07300213, -0.0438851 , -0.04977189, -0.04965674,
       -0.01129121,  0.07898265, -0.18369447, -0.06539592,  0.10144313,
        0.13284226, -0.10391603, -0.16402306,  0.24115917,  0.06384456,
       -0.21270277, -0.09763712,  0.01131041,  0.24192491,  0.24191548,
        0.05934096, -0.0148933 , -0.09553802,  0.19323507, -0.36326063,
        0.03090961,  0.14338984,  0.00279139, -0.01690601,  0.12196687,
       -0.18151924,  0.05995632,  0.2060522 , -0.26860544,  0.01498435,
       -0.00398036, -0.18841669, -0.06418969, -0.12336732,  0.23860565,
        0.10523669, -0.15339051, -0.07815976,  0.29447106

#### Distance Function and Resemblance
face_recognition.face_distance(face_encodings, f)<br>
Returns list of Euclidean distances of all face encodings in the list face_encodings from the face f

In [18]:
jenlaw1 = fr.load_image_file("celeb_dataset/Jennifer_Lawrence/092_aebdc10e.jpg")
jenlaw2 = fr.load_image_file("celeb_dataset/Jennifer_Lawrence/020_5a08581b.jpg")
jenlaw3 = fr.load_image_file("celeb_dataset/Jennifer_Lawrence/076_caf65a53.jpg")
megfox1 = fr.load_image_file("celeb_dataset/Megan_Fox/012_d461a2b5.jpg")
johndepp1 = fr.load_image_file("celeb_dataset/Johnny_Depp/098_16b30dda.jpg")
enc1 = fr.face_encodings(jenlaw1)[0]
enc2 = fr.face_encodings(jenlaw2)[0]
enc3 = fr.face_encodings(jenlaw3)[0]
enc4 = fr.face_encodings(megfox1)[0]
enc5 = fr.face_encodings(johndepp1)[0]
faces = [enc2, enc3, enc4, enc5]
d = fr.face_distance(faces, enc1)
print(d)

[0.42422033 0.41878663 0.73417251 0.80457631]


#### Mother - daughter Resemblance

In [19]:
n = 6

mothers = []
mother_encs = []
daughters = []
daughter_encs = []

# path templates for images
m_path_template = 'mother_daughter/mother{}.jpg'
d_path_template = 'mother_daughter/daughter{}.jpg'

# append face encodings to list
for i in range(1, n+1):
    m = fr.load_image_file(m_path_template.format(i))
    d = fr.load_image_file(d_path_template.format(i))
    mothers.append(m)
    mother_encs.append(fr.face_encodings(m)[0])
    daughters.append(d)
    daughter_encs.append(fr.face_encodings(d)[0])

cols = []
rows = []
lst = []
for i in range(1, n+1):
    cols.append('Mother {}'.format(i))
    rows.append('Daughter {}'.format(i))
    lst.append(fr.face_distance(mother_encs, daughter_encs[i-1]))

# convert list to data frame
df = pd.DataFrame(lst)
df.columns = cols
df.index = rows
print(df)

            Mother 1  Mother 2  Mother 3  Mother 4  Mother 5  Mother 6
Daughter 1  0.687214  0.719929  0.860692  0.744426  0.786763  0.848025
Daughter 2  0.740466  0.665743  0.768776  0.747291  0.715549  0.701961
Daughter 3  0.761065  0.695402  0.629270  0.718516  0.664736  0.792774
Daughter 4  0.726341  0.659520  0.740936  0.613277  0.657482  0.661698
Daughter 5  0.678506  0.722404  0.793655  0.741665  0.663127  0.759696
Daughter 6  0.750527  0.820560  0.789111  0.815145  0.804044  0.618579


#### Compare two faces
face_recognition.compare_faces([face_encs], unknown_face_encs, tolerance = 0.4) <br>
Default vaalue of tolerance = 0.5<br>
Returns list of boolean values for each element in face true if given faces match, false otherwise

In [20]:
compare = fr.compare_faces(faces, enc1, tolerance = 0.45)
for i in range(len(compare)):
    print('Face {}:'.format(i+1), end = ' ')
    if compare[i]:
        print("Jennifer Lawrence")
    else:
        print("Not Jennifer Lawrence")

Face 1: Jennifer Lawrence
Face 2: Jennifer Lawrence
Face 3: Not Jennifer Lawrence
Face 4: Not Jennifer Lawrence
